Mechanist Website/Controllers/AboutUsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Mechanist_Website.Data;
using Microsoft.AspNetCore.Mvc;
using Mechanist_Website.Models;

namespace Mechanist_Website.Controllers
{
    public class AboutUsController : Controller
    {
        private readonly DataContext _context;

        public AboutUsController(DataContext context)
        {
            _context = context;
        }
        public ActionResult Index()
        {
            List<MembersInfo> membersInfo = _context.Members.ToList();
            return View(membersInfo);
        }
    }
}

Mechanist Website/Controllers/DownloadsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Mechanist_Website.Models;
using Mechanist_Website.Data;
using Microsoft.AspNetCore.Mvc;
using System.IO;

namespace Mechanist_Website.Controllers
{
    public class DownloadsController : Controller
    {
        private readonly DataContext _context;

        public DownloadsController(DataContext context)
        {
            _context = context;
        }

        public ActionResult Index()
        {
            List<DownloadInfo> downloadInfo = _context.Downloads.ToList();
            downloadInfo.ForEach(d => d.Image = null);
            return View(downloadInfo);
        }

        public ActionResult Download(DownloadInfo dl)
        {
            return View(dl);
        }

        public FileResult FileDownload(string fileName)
        {
            byte[] fileBytes = System.IO.File.ReadAllBytes(@"wwwroot/Downloads/" + Path.GetFileName(fileName));
            return File(fileBytes, System.Net.Mime.MediaTypeNames.Application.Octet, fileName);
        }

        public FileContentResult getImg(int id)
        {
            try
            {
                byte[] byteArray = _context.Downloads.First(d => d.DownloadID == id).Image;
                return byteArray != null
                    ? new FileContentResult(byteArray, "image/jpeg")
                    : null;
            }
            catch (Exception e)
            {
                Console.WriteLine(e);
                return null;
            }
        }
    }
}

Mechanist Website/Controllers/ProjectsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Mechanist_Website.Models;
using Mechanist_Website.Data;

namespace Mechanist_Website.Controllers
{
    public class ProjectsController : Controller
    {
        private readonly DataContext _context;

        public ProjectsController(DataContext context)
        {
            _context = context;
        }

        public ActionResult Index()
        {
            List<ProjectInfo> projectInfo = _context.Projects.ToList();
            projectInfo.ForEach(p => p.Image = null);
            return View(projectInfo);
        }

        public ActionResult Project(ProjectInfo project)
        {
            return View(project);
        }

        public FileContentResult getImg(int id)
        {
            try
            {
                byte[] byteArray = _context.Projects.First(d => d.ProjectID == id).Image;
                return byteArray != null
                    ? new FileContentResult(byteArray, "image/jpeg")
                    : null;
            }
            catch (Exception e)
            {
                Console.WriteLine(e);
                return null;
            }
        }
    }
}

Mechanist Website/Views/Shared/_Favicons.cshtml
<link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png">
<link rel="icon" type="image/png" href="/favicon-32x32.png" sizes="32x32">
<link rel="icon" type="image/png" href="/favicon-16x16.png" sizes="16x16">
<link rel="manifest" href="/manifest.json">
<link rel="mask-icon" href="/safari-pinned-tab.svg" color="#5bbad5">
<meta name="theme-color" content="#00ffff">

Mechanist Website/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<style>
    nav {
        margin-bottom: 0;
        padding-bottom: 0;
    }
</style>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Mechanist</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    @await Html.PartialAsync("_Favicons")
</head>

<body class="bg-secondary">
    <header style="height: 10%">
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark border-bottom box-shadow">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index"><img src="~/images/mechanists_logo_transparent.png" alt="Mechanists Logo" style="width:60px"> Mechanists</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse float-right">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Projects" asp-action="Index">Projects</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Downloads" asp-action="Index">Downloads</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="AboutUs" asp-action="Index">About Us</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" href="http://mechanists.org/maps/index.html#/-121/64/-183/-10/survival%20-%20overworld/survivalday">SMP Map</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <main role="main" style="width: 100%">
        @RenderBody()
    </main>

    <footer class="border-top bg-dark footer text-muted">
        <div class="container">
            &copy; 2020 - Mechanists - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>