Mechanist Website/Controllers/ManageMemberController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Mechanist_Website.Data;
using Mechanist_Website.Models;
using Microsoft.AspNetCore.Authorization;
using System.Security.Claims;

namespace Mechanist_Website.Controllers
{
    [Authorize(Policy = "IsAdmin")]
    public class ManageMemberController : Controller
    {
        private readonly DataContext _context;

        public ManageMemberController(DataContext context)
        {
            _context = context;
        }

        // GET: ManageMember
        public async Task<IActionResult> Index()
        {
            return View(await _context.Members.ToListAsync());
        }

        // GET: ManageMember/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var membersInfo = await _context.Members
                .FirstOrDefaultAsync(m => m.MemberID == id);
            if (membersInfo == null)
            {
                return NotFound();
            }

            return View(membersInfo);
        }

        // GET: ManageMember/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: ManageMember/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("MemberID,DiscordID,IsAdmin,DiscordName,MCName,Name,DateAccepted,Twitch,Youtube,Website,Retired")] MembersInfo membersInfo)
        {
            if (ModelState.IsValid)
            {
                _context.Add(membersInfo);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(membersInfo);
        }

        // GET: ManageMember/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var membersInfo = await _context.Members.FindAsync(id);
            if (membersInfo == null)
            {
                return NotFound();
            }
            return View(membersInfo);
        }

        // POST: ManageMember/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("MemberID,DiscordID,IsAdmin,DiscordName,MCName,Name,DateAccepted,Twitch,Youtube,Website,Retired")] MembersInfo membersInfo)
        {
            if (id != membersInfo.MemberID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(membersInfo);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!MembersInfoExists(membersInfo.MemberID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(membersInfo);
        }

        // GET: ManageMember/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var membersInfo = await _context.Members
                .FirstOrDefaultAsync(m => m.MemberID == id);
            if (membersInfo == null)
            {
                return NotFound();
            }

            return View(membersInfo);
        }

        // POST: ManageMember/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var membersInfo = await _context.Members.FindAsync(id);
            _context.Members.Remove(membersInfo);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool MembersInfoExists(int id)
        {
            return _context.Members.Any(e => e.MemberID == id);
        }
    }
}

Mechanist Website/Controllers/ManagementController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Mechanist_Website.Extensions;
using Mechanist_Website.Data;
using Mechanist_Website.Models;

namespace Mechanist_Website.Controllers
{
    public class ManagementController : Controller
    {
        private readonly DataContext _context;

        public ManagementController(DataContext context)
        {
            _context = context;
        }
        public ActionResult Index()
        {
            List<MembersInfo> membersInfo = _context.Members.ToList();
            return View(membersInfo);
        }

        [HttpGet("~/SignIn")]
        public async Task<IActionResult> SignIn() => View("SignIn", await HttpContext.GetExternalProvidersAsync());

        [HttpPost("~/SignIn")]
        public async Task<IActionResult> SignIn([FromForm] string provider)
        {
            // Note: the "provider" parameter corresponds to the external
            // authentication provider choosen by the user agent.
            if (string.IsNullOrWhiteSpace(provider))
            {
                return BadRequest();
            }

            if (!await HttpContext.IsProviderSupportedAsync(provider))
            {
                return BadRequest();
            }

            // Instruct the middleware corresponding to the requested external identity
            // provider to redirect the user agent to its own authorization endpoint.
            // Note: the authenticationScheme parameter must match the value configured in Startup.cs
            return Challenge(new AuthenticationProperties { RedirectUri = "/" }, provider);
        }

        [HttpGet("~/SignOut")]
        [HttpPost("~/SignOut")]
        public IActionResult SignOut()
        {
            // Instruct the cookies middleware to delete the local cookie created
            // when the user agent is redirected from the external identity provider
            // after a successful authentication flow (e.g Google or Facebook).
            return SignOut(new AuthenticationProperties { RedirectUri = "/" },
                CookieAuthenticationDefaults.AuthenticationScheme);
        }
    }
}

Mechanist Website/Views/ManageMember/Create.cshtml
@model Mechanist_Website.Models.MembersInfo

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>MembersInfo</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="DiscordID" class="control-label"></label>
                <input asp-for="DiscordID" class="form-control" />
                <span asp-validation-for="DiscordID" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="IsAdmin" /> @Html.DisplayNameFor(model => model.IsAdmin)
                </label>
            </div>
            <div class="form-group">
                <label asp-for="DiscordName" class="control-label"></label>
                <input asp-for="DiscordName" class="form-control" />
                <span asp-validation-for="DiscordName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MCName" class="control-label"></label>
                <input asp-for="MCName" class="form-control" />
                <span asp-validation-for="MCName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DateAccepted" class="control-label"></label>
                <input asp-for="DateAccepted" class="form-control" />
                <span asp-validation-for="DateAccepted" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Twitch" class="control-label"></label>
                <input asp-for="Twitch" class="form-control" />
                <span asp-validation-for="Twitch" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Youtube" class="control-label"></label>
                <input asp-for="Youtube" class="form-control" />
                <span asp-validation-for="Youtube" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Website" class="control-label"></label>
                <input asp-for="Website" class="form-control" />
                <span asp-validation-for="Website" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="Retired" /> @Html.DisplayNameFor(model => model.Retired)
                </label>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

Mechanist Website/Views/ManageMember/Delete.cshtml
@model Mechanist_Website.Models.MembersInfo

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>MembersInfo</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DiscordID)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DiscordID)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IsAdmin)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IsAdmin)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DiscordName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DiscordName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.MCName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.MCName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DateAccepted)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DateAccepted)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Twitch)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Twitch)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Youtube)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Youtube)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Website)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Website)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Retired)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Retired)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="MemberID" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Mechanist Website/Views/ManageMember/Details.cshtml
@model Mechanist_Website.Models.MembersInfo

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>MembersInfo</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DiscordID)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DiscordID)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IsAdmin)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IsAdmin)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DiscordName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DiscordName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.MCName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.MCName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DateAccepted)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DateAccepted)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Twitch)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Twitch)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Youtube)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Youtube)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Website)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Website)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Retired)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Retired)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.MemberID">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Mechanist Website/Views/ManageMember/Edit.cshtml
@model Mechanist_Website.Models.MembersInfo

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>MembersInfo</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="MemberID" />
            <div class="form-group">
                <label asp-for="DiscordID" class="control-label"></label>
                <input asp-for="DiscordID" class="form-control" />
                <span asp-validation-for="DiscordID" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="IsAdmin" /> @Html.DisplayNameFor(model => model.IsAdmin)
                </label>
            </div>
            <div class="form-group">
                <label asp-for="DiscordName" class="control-label"></label>
                <input asp-for="DiscordName" class="form-control" />
                <span asp-validation-for="DiscordName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MCName" class="control-label"></label>
                <input asp-for="MCName" class="form-control" />
                <span asp-validation-for="MCName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DateAccepted" class="control-label"></label>
                <input asp-for="DateAccepted" class="form-control" />
                <span asp-validation-for="DateAccepted" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Twitch" class="control-label"></label>
                <input asp-for="Twitch" class="form-control" />
                <span asp-validation-for="Twitch" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Youtube" class="control-label"></label>
                <input asp-for="Youtube" class="form-control" />
                <span asp-validation-for="Youtube" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Website" class="control-label"></label>
                <input asp-for="Website" class="form-control" />
                <span asp-validation-for="Website" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="Retired" /> @Html.DisplayNameFor(model => model.Retired)
                </label>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

Mechanist Website/Views/ManageMember/Index.cshtml
@model IEnumerable<Mechanist_Website.Models.MembersInfo>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.DiscordID)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.IsAdmin)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DiscordName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.MCName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DateAccepted)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Twitch)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Youtube)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Website)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Retired)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.DiscordID)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.IsAdmin)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DiscordName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.MCName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DateAccepted)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Twitch)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Youtube)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Website)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Retired)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.MemberID">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.MemberID">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.MemberID">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

<a asp-action="Index" asp-controller="Management">Back to Management</a>